name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  quality:
    runs-on: ubuntu-latest
    name: Code Quality Checks

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check & build
        run: bun run build

      - name: Lint & format check
        run: bun run check

      - name: Test (when available)
        run: bun test || echo "✅ No tests configured yet"

      - name: Environment validation
        run: |
          echo "Checking environment configuration..."
          if [ -f "src/config/env.ts" ]; then
            echo "✅ Environment validation file exists"
          else
            echo "❌ Environment validation missing"
            exit 1
          fi